"use strict";
const urdu = 75;
const math = 45;
const english = 62;
const scinse = 55;
const grammer = 50;
const totalMarks = 500;
console.log(totalMarks);
const obtainedMarks = urdu + math + english + scinse + grammer;
console.log(obtainedMarks);
const percentage = obtainedMarks / totalMarks * 100;
console.log(percentage);
